# permissions for end users to view mystatefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devops-golang-test
    app.kubernetes.io/managed-by: kustomize
  name: mystatefulset-viewer-role
rules:
- apiGroups:
  - devops.github.com
  resources:
  - mystatefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.github.com
  resources:
  - mystatefulsets/status
  verbs:
  - get
