---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - devops.github.com
  resources:
  - mystatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.github.com
  resources:
  - mystatefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - devops.github.com
  resources:
  - mystatefulsets/status
  verbs:
  - get
  - patch
  - update
