apiVersion: devops.github.com/v1
kind: MyStatefulSet
metadata:
  labels:
    app.kubernetes.io/name: devops-golang-test
    app.kubernetes.io/managed-by: kustomize
  name: mss
spec:
  replicas: 3
  storageClass: standard
  gracePeriod: 5
  template:
    spec:
      containers:
      - name: redis
        image: quay.io/opstree/redis:latest
